[tool.black]
line-length = 88
target-version = ['py312']

extend-exclude = '''

(
  ^/myvenv
  | ^/.venv
  | ^/dist
  | ^/build
)
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
skip = ["myvenv", ".venv", "dist", "build"]
