faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "google"
  model_name: "text-embedding-004"

retriever:
  top_k: 10

llm:
  default_provider: "groq"
  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0.2
    max_output_tokens: 2048
  groq:
    provider: "groq"
    model_name: "llama-3.3-70b-versatile"
    temperature: 0
    max_output_tokens: 2048
